camera_fx: 725.0087
camera_fy: 725.0087
camera_cx: 620.5
camera_cy: 187.0

points_too_far_threshold: 30.0
points_too_close_threshold: 0.5

min_vote_number_threshold: 3
min_iou_threshold: 0.4
min_bbox_size_threshold: 2000.0
